### ISSUE TITLE
Add - in python

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#1]
https://github.com/tasnimzotder/hactoberfest-2020/blob/4ae62e2b1072cee67a585e6bdc0cab49faedcdf2/python/add.py#L4

Write code to add two numbers in python

**Comment by GSNCodes** [comment]
I would like to work on this. Could you assign this to me ? @tasnimzotder

**Comment by tasnimzotder** [comment]
Sure

**Comment by Sayak11** [comment]
Can I work on it and add few more functions @tasnimzotder ?

**Comment by tasnimzotder** [comment]
> Can I work on it and add few more functions @tasnimzotder ?
> 

Yes you can 👍
