### ISSUE TITLE
Binary Tree in python

### ISSUE THREAD

**Issue by UsamaKashif** [tasnimzotder/hacktoberfest-2020#124]
I will add a binary tree data structure using python.

**Comment by tasnimzotder** [comment]
hey @UsamaKashif, you're welcome to add new codes/features. You just need to follow the guideline.

**Comment by UsamaKashif** [comment]
What are the guidelines?

**Comment by tasnimzotder** [comment]
You can follow the [contributing guideline](https://github.com/tasnimzotder/hacktoberfest-2020/blob/master/CONTRIBUTING.md) and to learn about `PR`, you can follow the [README](https://github.com/tasnimzotder/hacktoberfest-2020/blob/master/README.md) documentation.
