### ISSUE TITLE
Add new html element

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#2]
https://github.com/tasnimzotder/hactoberfest-2020/blob/54e3f24109aafded9929f7a21a23d03056499dc0/html/index.html#L11

**Comment by CilgaIscan** [comment]
I would like to work on this as a first project. Could you assign this to me ? @tasnimzotder

**Comment by tanushree57** [comment]
Hi could I contribute to this?

**Comment by tasnimzotder** [comment]
@tanushree57 Yes

**Comment by Dheeraj-kumar626** [comment]
@tasnimzotder 
Can you specify what modifications need to be done?
i'm new to open source..is this section the platform for communication?

**Comment by tasnimzotder** [comment]
@Dheeraj-kumar626 
You can modify the `html` file.
For example the `body` section of the `html` file, you can add a new `h2` element and inside that you can write one of your favourite senstences. Like - 
```html
<h2>The power of Open Source is the power of the people. The people rule.</h2>
```

**Comment by singhshivansh244** [comment]
@tasnimzotder 
I'm also contributing!!!
I'll be adding some small changes.
