### ISSUE TITLE
Make a hackbar 🍫 and open a PR

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#21]
# Open a PR by creating your hackbar 🍫.

![image](https://user-images.githubusercontent.com/44049528/94300621-e4599c80-ff86-11ea-9c5a-62efef69ad62.png)

**Comment by Anita-ihuman** [comment]
Can I tackle this issue?

**Comment by chamiduu** [comment]
I would work on this gladly, can you assign me for this issue?

**Comment by tasnimzotder** [comment]
@chamindujs You can directly add a `hackbar` and open a `PR`

Follow the documentation 👉 https://github.com/tasnimzotder/hacktoberfest-2020/blob/master/README.md

**Comment by rishavjaiss** [comment]
Hi, I'll be glad to do this! It's my first time in Hacktoberfest.

**Comment by RushiVachhani** [comment]
Is this issue open for everyone ??

**Comment by tasnimzotder** [comment]
@RushiVachhani Yes, this issue is open for everyone

**Comment by yashikacac** [comment]
Hi @tasnimzotder , I would like to work on this issue.

**Comment by tasnimzotder** [comment]
@yashikacac thanks for your interest. You can open a`PR` by going through the [documentation](https://github.com/tasnimzotder/hacktoberfest-2020/blob/master/README.md)

**Comment by yashikacac** [comment]
Don't let your actions harm Earth #62

**Comment by vighneshdeepweb** [comment]
Hii can i work on this task??

**Comment by vighneshdeepweb** [comment]
pls review 

#97

**Comment by tasnimzotder** [comment]
@kaash-bot Sure

**Comment by tasnimzotder** [comment]
Hacktoberfest 2020 is over. 🎉
Let's make our wishes on climate change and open-source true.
