### ISSUE TITLE
JavaScript - Write functions to Add, Subtract, Multiply & Divide two numbers

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#28]
https://github.com/tasnimzotder/hacktoberfest-2020/blob/fdf137d0217307c5a66f770c49db8a8835af9f65/javascript/calculations.js#L1

**Comment by gokulkannan7** [comment]
Sir, can I complete this task?

**Comment by tasnimzotder** [comment]
@gokulkannan7 Offcourse you can.
You are welcome here.

**Comment by gokulkannan7** [comment]
One doubt sir, should I open a PR in October since its a part of hacktoberfest?

**Comment by tasnimzotder** [comment]
@gokulkannan7 For the learning purpose you can open a `PR` before October.
And if you want to make your `PR` as a part of `hacktoberfest`, you need to open the `PR` on October only.

**Comment by gokulkannan7** [comment]
thank you sir, I'll start working on it, can you assign it to me?

**Comment by skamp91** [comment]
Hey :) is it possible that I also complete the Task? 
Good Regards :)

**Comment by tasnimzotder** [comment]
@skamp91 this issue is already assigned to @gokulkannan7. We can open a similar issue for you.

**Comment by skamp91** [comment]
@tasnimzotder  oh yes that qould be very nice 👍

**Comment by tasnimzotder** [comment]
@skamp91 Your issue is ready #33

**Comment by vikhyatsingh123** [comment]
Hey! Can I also complete any task or solve any issue

**Comment by gokulkannan7** [comment]
@tasnimzotder Hey I have opened a PR, pls check

**Comment by tasnimzotder** [comment]
@gokulkannan7 Okay. Let me check.
