### ISSUE TITLE
JavaScript - Find area of circle, square & rectangle

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#33]
https://github.com/tasnimzotder/hacktoberfest-2020/blob/28875144601b014b08e0f38d81040851dbf398b5/javascript/area.js#L1

**Comment by skamp91** [comment]
thx a lot
then assign me please :)

**Comment by joey2031** [comment]
Is anyone doing Find area of circle, square & rectangle? If not I would love to do this. Thanks!

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue.
