### ISSUE TITLE
Python - Sum of the elements of an array

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#7]
https://github.com/tasnimzotder/hactoberfest-2020/blob/f174f45ae15c7c742439891576636fae5b2b2957/python/array_sum.py#L4

**Comment by hritik5102** [comment]
Hello @tasnimzotder , I would like to contribute to this issue, all python code in your repository

**Comment by tasnimzotder** [comment]
Hi @hritik5102 you are welcome to contribute.

**Comment by CilgaIscan** [comment]
Hi @tasnimzotder , I would like to contribute to this issue

**Comment by pranavbharadwaj007** [comment]
sir @tasnimzotder I have contributed to this problem pls accept my pull request
