### ISSUE TITLE
Python - Even or Odd

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#8]
https://github.com/tasnimzotder/hactoberfest-2020/blob/f174f45ae15c7c742439891576636fae5b2b2957/python/even_odd.py#L4

**Comment by hritik5102** [comment]
Hello @tasnimzotder , I would like to contribute to this issue, all python code in your repository

**Comment by CilgaIscan** [comment]
Hi  @tasnimzotder , I would lite to work on this!

**Comment by Sayak11** [comment]
Hi @tasnimzotder  sie I would like to work on it

**Comment by tasnimzotder** [comment]
You can modify the function and make a PR

**Comment by Dheeraj-kumar626** [comment]
Hii @tasnimzotder i'm willing to contribute to this issue
