### ISSUE TITLE
Python - Factorial

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2020#9]
https://github.com/tasnimzotder/hactoberfest-2020/blob/f174f45ae15c7c742439891576636fae5b2b2957/python/factorial.py#L4

**Comment by hritik5102** [comment]
Hello @tasnimzotder , I would like to contribute to this issue, all python code in your repository

**Comment by CilgaIscan** [comment]
Hi @tasnimzotder , I would like to contribute!

**Comment by Sayak11** [comment]
Hello @tasnimzotder Sir, I would like to contribute

**Comment by rahulk31** [comment]
Hi @tasnimzotder , it would be a pleasure to contribute in your repo,please add me

**Comment by pranavbharadwaj007** [comment]
Hi @tasnimzotder , sir I would like to contribute.
